version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - RAILS_ENV=production
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/rails

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: {}
